#!/usr/bin/env bash
# Isolated Noctalia preview of the plugin inside a nested Hyprland window.
#
#   scripts/preview.sh run         start the preview in the foreground; Ctrl-C stops it
#   scripts/preview.sh config      write and validate the preview config only
#   scripts/preview.sh panel       toggle the plugin panel in the preview
#   scripts/preview.sh shot FILE   save a screenshot of the preview (needs grim)
#   scripts/preview.sh clean       remove preview and fixture runtime files
#
# Nothing here touches your running shell: the preview has its own Wayland
# display, D-Bus session, and Noctalia config/state/data directories under
# $XDG_RUNTIME_DIR/astral-monitor-preview. Pair it with the fixture source
# (make fixture); it never reads hardware.
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
: "${XDG_RUNTIME_DIR:?XDG_RUNTIME_DIR must be set}"
PREVIEW_DIR=${ASTRAL_PREVIEW_DIR:-$XDG_RUNTIME_DIR/astral-monitor-preview}
FIXTURE_PATH=${ASTRAL_FIXTURE_PATH:-$XDG_RUNTIME_DIR/astral-monitor-fixture/snapshot.json}
DISPLAY_FILE=$PREVIEW_DIR/wayland-display
PID_FILE=$PREVIEW_DIR/pid
PLUGIN_ID=mtrenker/astral_monitor

die() { echo "preview: $*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "$1 not found on PATH"; }

# The nested display, only while the preview process lives, so commands can never reach your own shell.
preview_display() {
  [[ -s $PID_FILE && -s $DISPLAY_FILE ]] && kill -0 "$(<"$PID_FILE")" 2>/dev/null \
    || die "no preview running (start it with: scripts/preview.sh run)"
  local display
  display=$(<"$DISPLAY_FILE")
  [[ -n $display && $display != "${WAYLAND_DISPLAY:-}" && -S $XDG_RUNTIME_DIR/$display ]] \
    || die "preview display '$display' is not live"
  printf '%s' "$display"
}

preview_live() { ( preview_display ) >/dev/null 2>&1; }

write_config() {
  mkdir -p "$PREVIEW_DIR"/{config/noctalia,state,data,cache}
  cat >"$PREVIEW_DIR/config/noctalia/config.toml" <<EOF
# Generated by scripts/preview.sh for an isolated fixture preview.
[shell]
setup_wizard_enabled = false
offline_mode = true
telemetry_enabled = false
polkit_agent = false
clipboard_enabled = false

[wallpaper]
enabled = false

[theme]
mode = "dark"
source = "builtin"
builtin = "Tokyo-Night"

[theme.templates]
enable_builtin_templates = false
enable_community_templates = false

[notification]
enable_daemon = false

[system.monitor]
enabled = false

[dock]
enabled = false

[desktop_widgets]
enabled = false

[plugins]
enabled = ["$PLUGIN_ID"]
auto_update = "none"

[[plugins.source]]
name = "official"
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
enabled = false

[[plugins.source]]
name = "community"
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
enabled = false

[[plugins.source]]
name = "astral-dev"
kind = "path"
location = "$ROOT/noctalia"
enabled = true

[plugin_settings."$PLUGIN_ID"]
snapshot_path = "$FIXTURE_PATH"

# Two instances of the widget share one service and one snapshot reader.
[bar.main]
position = "top"
start = ["astral_a"]
center = ["clock"]
end = ["astral_b"]

[widget.astral_a]
type = "$PLUGIN_ID:bar"

[widget.astral_b]
type = "$PLUGIN_ID:bar"
EOF

  cat >"$PREVIEW_DIR/hyprland.lua" <<EOF
-- Generated by scripts/preview.sh: nested compositor for the fixture preview.
hl.monitor({ output = "", mode = "1440x900", position = "auto", scale = "1" })
hl.env("NOCTALIA_CONFIG_HOME", "$PREVIEW_DIR/config")
hl.env("NOCTALIA_STATE_HOME", "$PREVIEW_DIR/state")
hl.env("NOCTALIA_DATA_HOME", "$PREVIEW_DIR/data")
hl.env("XDG_CACHE_HOME", "$PREVIEW_DIR/cache")
hl.config({
  ecosystem = { no_update_news = true, no_donation_nag = true },
  misc = { disable_hyprland_logo = true, disable_splash_rendering = true },
})
hl.on("hyprland.start", function()
  hl.exec_cmd("printf %s \"\$WAYLAND_DISPLAY\" > '$DISPLAY_FILE'")
  hl.exec_cmd("noctalia > '$PREVIEW_DIR/noctalia.log' 2>&1")
end)
EOF
}

cmd_run() {
  need Hyprland
  need dbus-run-session
  need noctalia
  ! preview_live || die "a preview is already running on $(<"$DISPLAY_FILE")"
  write_config
  rm -f "$DISPLAY_FILE"
  echo $$ >"$PID_FILE"
  noctalia config validate "$PREVIEW_DIR/config/noctalia/config.toml" >/dev/null \
    || die "generated Noctalia config is invalid"
  [[ -e $FIXTURE_PATH ]] || echo "preview: no snapshot at $FIXTURE_PATH yet; start 'make fixture' to feed it"
  echo "Preview: nested Hyprland with an isolated Noctalia (Tokyo-Night, fixture snapshot)."
  echo "Snapshot: $FIXTURE_PATH"
  echo "Noctalia log: $PREVIEW_DIR/noctalia.log"
  echo "Toggle the panel with: make preview-panel    Stop with Ctrl-C."
  # start-hyprland is Hyprland's supported launcher; plain Hyprland works but shows a warning.
  if command -v start-hyprland >/dev/null 2>&1; then
    exec dbus-run-session -- start-hyprland -- --config "$PREVIEW_DIR/hyprland.lua"
  fi
  exec dbus-run-session -- Hyprland --config "$PREVIEW_DIR/hyprland.lua"
}

cmd_panel() {
  local display
  display=$(preview_display)
  WAYLAND_DISPLAY=$display noctalia msg panel-toggle "$PLUGIN_ID:panel"
}

cmd_shot() {
  need grim
  local display out=${1:?usage: scripts/preview.sh shot FILE}
  display=$(preview_display)
  WAYLAND_DISPLAY=$display grim "$out"
  echo "$out"
}

cmd_clean() {
  if preview_live; then
    die "preview still running; stop it with Ctrl-C first"
  fi
  rm -rf -- "$PREVIEW_DIR" "$(dirname "$FIXTURE_PATH")"
  echo "Removed $PREVIEW_DIR and $(dirname "$FIXTURE_PATH")"
}

case ${1:-run} in
  run) cmd_run ;;
  config) write_config; noctalia config validate "$PREVIEW_DIR/config/noctalia/config.toml" ;;
  panel) cmd_panel ;;
  shot) shift; cmd_shot "$@" ;;
  clean) cmd_clean ;;
  *) die "unknown command '$1' (run, config, panel, shot FILE, clean)" ;;
esac
